# Department Service Configuration

spring.datasource.url=jdbc:mysql://localhost:3306/department_db
spring.datasource.username=root
spring.datasource.password=SQL__7am

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

eureka.instance.prefer-ip-address=true
#Using Feign API client
feign.client.employee-service.url=http://localhost:8081

#Configuring the path for the Eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Messsage to read in the application (runtime change without restart using actuator refresh)
spring.boot-config.message = Hello, Department service.
